### ISSUE TITLE
Allow checkouts to be cached

### ISSUE THREAD

**Issue by rhysforyou** [tmspzz/Rome#177]
## Enhancement Suggestion 

It would be helpful if, in addition to built frameworks, Rome could also cache the contents of the _Checkouts_ directory.

**Current behavior**

Only the built frameworks are cached.

**Suggested behavior**

Both built frameworks and checkouts are cached.

**Why would the enhancement be useful to most users**

For a lot of projects, we want the guarantee that we can still build them if dependencies are removed from GitHub, or tags are changed / removed. For this purpose, some developers choose to include the _Checkouts_ directory in their git repo, however this has some notable downsides in terms of repository size, noise in pull requests, etc.

It seems like this problem could be quite elegantly solved by including Checkouts in the files that are backed up by Rome.

**Rome version:** 

0.20.0.56 - Romam uno die non fuisse conditam.

**OS and version:** 

macOS Mojave Version 10.14.4 (18E226)

**Comment by blender** [comment]
I think that if you are worried the scenarios you describe then you should fork the repositories instead and use that.

I don't believe this is something that should be Rome's responsibility.

**Comment by tedgonzalez** [comment]
Does it make sense to create a custom engine that does this?

**Comment by tmspzz** [comment]
I don’t think it’s even possible as information needed to do so is not passes to engine, and from the engine it cannot be passed back to Rome. 

Even if it could, that would be a bad practice.  Don’t store copy of source code on S3 or what not. Source control (git, mercurial, svn) has been invented to tackle exactly this problem. 

Just fork the repositories and push them to a remove you control (GitHub, stash, gitlab... or you private git server). 

I didn’t make Rome to solve source file backup. There is version control for that.
