### ISSUE TITLE
Using rome upload fails before calling engine

### ISSUE THREAD

**Issue by aturlier** [tmspzz/Rome#215]
## Bug Report 

When using Rome with an engine, upload fails after zipping the first framework. list works fine

**Steps which explain the enhancement or reproduce the bug**
Here's my Romefile : 
```yaml
cache:
  engine: RomeEngine.sh
```

The RomeEngine script starts with this :

```bash
#!/bin/sh

echo "Rome Engine Called"
```

`rome upload -v` output :

```
16:16:34 2020-02-06 - Starting to zip: Carthage/Build/iOS/Alamofire.framework
rome: Alamofire/iOS/Alamofire.framework-5.0.0-rc.3.zip: openBinaryFile: inappropriate type (Is a directory)
```

My script isn't called.

**Rome version:** 

    0.23.2.63

**OS and version:** 

   macOS Catalina 10.15.2

**Comment by tmspzz** [comment]
My guess is that `Alamofire.framework-5.0.0-rc.3.zip` is a directory. Did you tamper with cache?

**Comment by aturlier** [comment]
I did not. I tried deleting the Carthage folder, running `carthage bootstrap --platform iOS --no-use-binaries`, then `rome upload -v`. The same thing happens : 

```
09:28:59 2020-02-07 - Starting to zip: Carthage/Build/iOS/Alamofire.framework
rome: Alamofire/iOS/Alamofire.framework-5.0.0-rc.3.zip: openBinaryFile: inappropriate type (Is a directory)
```

When changing the Romefile to a local cache, the zipping is successful. I don't think the issue comes from my script, as it sin't even called.

Here is my Cartfile if you want  : 
```
github "Moya/Moya" ~> 14.0.0-beta.6
github "Swinject/Swinject"
github "onevcat/Kingfisher" "5.7.1"
github "ReactiveX/RxSwift" ~> 5.0
```

**Comment by aturlier** [comment]
Okay I found the error.

I had some folders that weren't deleted from a previous canceled `rome upload`, and rome was having trouble with that
