### ISSUE TITLE
Internal dependencies are Built every time

### ISSUE THREAD

**Issue by varunrathi28** [tmspzz/Rome#216]
## Enhancement Suggestion / Bug Report 

    Support for internal dependencies.

**Steps which explain the enhancement or reproduce the bug**
1. I have a carthage dependency called "facebook-objc-sdk".
2. Cartfile.Resolved contains the entry for "facebook-obj-sdk" with "Version".
3. On running bootstrapping, carthage downloads internal dependencies like FacebookLogin.framework, FacebookCore.framework which aren't in the carthage.resolved.
4. So when i run rome upload, it does not cache those internal dependencies, which take too long.

**Current behavior**

    Downloads and builds internal dependencies every time.

**Suggested behavior**

    Should cache those depencies

**Why would the enhancement be useful to most users**

   a way to create a map of internal dependecies 

**Rome version:** 

    0.23.2.63

**OS and version:** 

    macOS Catalina v 10.15.3

**Comment by tmspzz** [comment]
Can you elaborate on "Internal dependencies"? 

maybe this is what you need? https://github.com/tmspzz/Rome#multiple-aliases

**Comment by tmspzz** [comment]
@varunrathi28 did my suggestion solve your problem?

**Comment by tmspzz** [comment]
Closing the issue for inactivity. Feel free to comment and I'll reopen
