### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by didix21** [tmspzz/Rome#223]
## Enhancement Suggestion

   Can be insteresting to add a CHANGELOG.md in order to see the main changes between Rome versions.
    
**Steps which explain the enhancement or reproduce the bug**

1. You could use a tool like: [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) wich can help to create it automatically.

**Comment by tmspzz** [comment]
Sounds like a good idea. Can you help set this up?

**Comment by didix21** [comment]
yes, I can give a hand with this.

**Comment by tmspzz** [comment]
Merged. Thanks again
