### ISSUE TITLE
Xcode version specific upload/download

### ISSUE THREAD

**Issue by jazz-mobility** [tmspzz/Rome#227]
## Enhancement Suggestion

First of all many thanks for this great tool, it saved a lot of time for us.
I would like to propose a new enhancement to support the upload and downloads based on xcode version.
As a big iOS team, we are using multiple versions of XCode cmd and it is really hard to move everyone at once. We are facing issues where binaries are conflicting swift version issues.
on CI, we use Xcode 11.4 which builds Swift 5.2 binaries but sometimes on local peers upload the binaries built with Xcode 11.3 (Swift 5.1) which causes the dependencies to build again.

I propose to have a folder structure on AWS S3 based on the Xcode cmd tool version. (xcode-select -v), each folder represents Xcode version, and binaries should be uploaded inside each folder.

**Steps which explain the enhancement**

1. Use Xcode 11.4 (Swift 5.2) cmd tools to build and upload binaries
2. change cmd tools to 11.3 (Swift 5.1)
3. Check that some dependencies are building again because of swift version incompatibility.

**Current behavior**

    - Currently, Rome uploads all binaries to the root of the S3 bucket with a folder for each dependency.

**Suggested behavior**

    - Probably, a folder with each (major.minor.x)version of XCode to upload binaries or may be based on the Swift version.

**Why would the enhancement be useful to most users**

- It will save build time for incompatible swift version.

**Rome version:** 

    0.23.2.63 - Romam uno die non fuisse conditam.

**OS and version:** 

macOS Catalina 10.15.4

**Comment by tmspzz** [comment]
@jazz-mobility have you tried using `--cache-prefix`? it is exactly for this purpose

**Comment by jazz-mobility** [comment]
Thanks @tmspzz 
I will use it. Sorry, I missed it from the Readme.

**Comment by tmspzz** [comment]
@jazz-mobility let me know if this solves it for you. If it does consider closing the issue.

**Comment by jazz-mobility** [comment]
Thanks @tmspzz It worked. Closing the issue.
