### ISSUE TITLE
Concurrent downloads for remote cache

### ISSUE THREAD

**Issue by dalu93** [tmspzz/Rome#228]
## Enhancement Suggestion

Would it be possible to have concurrent downloads while fetching the cached data, either through custom engine or S3 bucket?

**Steps which explain the enhancement or reproduce the bug**

An example application usually have around 5-10 dependencies. Even if the download speed is good enough, this is taking more than 1 minute (in my specific case, 5 minutes). I believe that, by running concurrently, the time spent on fetching the cached data would decrease.

**Rome version:** 

0.23.3.64 - Romam uno die non fuisse conditam.

**OS and version:** 

MacOS Mojave 10.14.6

**Comment by tmspzz** [comment]
https://github.com/tmspzz/Rome#uploading 


> Since version 0.20.0.56, if you are on a fast Internet connection you can use the `--concurrently`  flag to maximise concurrency for the operation and maximise bandwith use. Using the `--concurrently` flag should result in a x3 speedup.
