### ISSUE TITLE
Losing debug capability when using cached builds downloaded by Rome

### ISSUE THREAD

**Issue by congnd** [tmspzz/Rome#232]
## Enhancement Suggestion

Losing debug capability when using cached builds downloaded by Rome.

**Steps which explain the enhancement or reproduce the bug**

1. Build and cache using Rome
2. Delete all Carthage's DerivedData in `/Users/USER/Library/Caches/org.carthage.CarthageKit/DerivedData/`
3. Delete the `Carthage` folder in the project
4. Download cached builds via Rome

**Current behavior**

I got this error from Xcode's console when trying to print variables by using the `po` or `p` command:
```
error: virtual filesystem overlay file '/Users/USER/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/lottie-ios/3.1.8/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_iOS/IntermediateBuildFilesPath/Lottie.build/Release-iphoneos/Lottie_iOS.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

**Suggested behavior**

Users should be able to debug as normal.

**Why would the enhancement be useful to most users**

It's obvious that having the debug capability in the development is necessary

**Rome version:** 

0.23.3.64

**OS and version:** 

macOS 10.15.5

**Comment by tmspzz** [comment]
I don't believe this is a problem with Rome. This might be due to the fact that you haven't built for distribution. You would have the same problem simply downloading a binary built somewhere else than your machine.

**Comment by vandyshev** [comment]
@congnd, i found solution in https://steipete.com/posts/couldnt-irgen-expression/
You can try delete all dSYM from /Carthage/Build/iOS folder. It helps for me.
