### ISSUE TITLE
Needs to be updated to support XCFrameworks.

### ISSUE THREAD

**Issue by 1oo7** [tmspzz/Rome#238]
Rome needs to be updated to support uploading XCFrameworks. Currently it only works with frameworks, which are deprecated.

**Comment by mpdifran** [comment]
Now that [Carthage 0.37.0](https://github.com/Carthage/Carthage/releases/tag/0.37.0) is out, it's required to build using xcframeworks (this is what I'm seeing for my project, not sure if this is entirely the case). 

Any idea on when work can get started on this? Is it as easy as changing the list of files to cache?

**Comment by tmspzz** [comment]
@mpdifran you can check the referenced PR for more details

**Comment by mpdifran** [comment]
Oops, I somehow missed that. Thanks!

**Comment by DrewKiino** [comment]
Hey fellow developers, so we all know that achieving remote caching is important for many of us especially in upcoming startups and such. There isn't much tooling out there that helps us achieve this and given that `.xcframeworks` has come into the mix, most of us are waiting on existing tooling to update as well as unfortunate as that sounds.

So my team and I went ahead and built **[Punic](https://github.com/summerlabs/punic)** as we couldn't wait any longer for existing tools to catch up.

Feel free to check out the CLI, it exclusively supports `.xcframework` and `aws` for remote caching and our company has been using it for the past month or so in our CI pipeline. Finally moving up to iOS 14.0. Feel free to check it out and let us know if this helps.

**Comment by acecilia** [comment]
You can also write some bash and:
1. Compress your `Carthage` folder
2. Upload it to the cloud, using the sha of the cartfile.resolved as the identifier

When downloading:
1. Use the sha of the cartfile.resolved to download the archive
2. Unpack the archive, getting the `Carthage` folder in place

**Comment by tmspzz** [comment]
> You can also write some bash

Sure, but it's to avoid uploading/downloading the entire folder and to be able to share single cached binaries the reason why I wrote this tool in the first place. 

The are other solutions that just do exactly that.

**Comment by acecilia** [comment]
@tmspzz Sure, thanks 🙌 

I just wanted to comment it in case it is helpful. We were using rome, but after some time we realized that our carthage dependencies (1GB) are only 400MB compressed, and we dont change them so usually, so downloading/uploading the whole folder is a good compromise: 400MB with a good internet connection takes very short time.

Then we use bazel to avoid re-downloading it every time, but if you want to avoid downloading if the carthage cache is already correct its also possible: just get a sha of all the contents of the `Carthage` folder and compare it with the sha of the cached folder (which you can place as the name of the `tar.gz` archive): if sha matches, `Carthage` folder is correct, otherwise re-download

**Comment by mpdifran** [comment]
@tmspzz I'm not super familiar on the Rome codebase, but please let me know how I can help review / test to get this over the line!

**Comment by tmspzz** [comment]
@tmspzz @vikrem @evandcoleman  Released as `v0.24.0.65` 🥳

**Comment by choli** [comment]
That's very cool, thanks a lot. We still have one fat framework (.framework instead of .xcframework) in the dependency collection. Do you know, how we can mix xcframeworks and this one framework the best way with these changes?

**Comment by mpdifran** [comment]
@choli I'm pretty sure you have to go "all in" with XCFrameworks to leverage this new flag. I think that's the case for both Carthage and Rome.

**Comment by tmspzz** [comment]
> That's very cool, thanks a lot. We still have one fat framework (.framework instead of .xcframework) in the dependency collection. Do you know, how we can mix xcframeworks and this one framework the best way with these changes?

Run Rome twice?

**Comment by choli** [comment]
Ok, running Rome twice was my first approach and yes, it does work. So I'll keep it that way. Thanks 👍🏽
