### ISSUE TITLE
When using currentMap its not possible to reuse the generated binaries

### ISSUE THREAD

**Issue by acecilia** [tmspzz/Rome#241]
Hey 👋 

I may be missunderstanding how `currentMap` works, but here is my situation.

**The problem**
I do run rome with `currentMap`, something like:
```
currentMap:
- project-name:
  - name: SomeBinary
    platforms: [iOS]
```

My repository does not have a tag, so the binary that gets uploaded to the cache looks as follows:

`Google Engine: uploading SomePath/project-name/iOS/SomeBinary.framework-e420d2156824da73be067b7c0b7a8b72e83b33d1.zip to SomePath/project-name/iOS/SomeBinary.framework-e420d2156824da73be067b7c0b7a8b72e83b33d1.zip
`

Note there that `e420d2156824da73be067b7c0b7a8b72e83b33d1` is the result of `git rev-parse HEAD`, which is the current commit hash.

Then I commit something else, and now my commit hash is `9b81fe146aa61b6477df7ed670aaca8308edbcd1`. I try to rome download the previously uploaded binary, but got in the console the following errors:

`Google Engine: SomePath/project-name/iOS/SomeBinary.framework-9b81fe146aa61b6477df7ed670aaca8308edbcd1.zip does not exist`

Which makes sense, because now the commit hash used as the version while downloading does not match the commit hash used as the version when uploading.

But then, how can I cache and consume the current binary? Am I miss-using the `currentMap`? How is this intended to be used?
Thanks! 🙏 

**Rome version:** 

    v0.23.3.64

**OS and version:** 

    Catalina 10.15.7

**Comment by tmspzz** [comment]
It works like Carthage's `--no-skip-current`.

The binary procured by the `HEAD` at the time of running the command is cached. If there is a tag the binary will be cached under the tag instead of the hash. 

It's supposed to be used in CI workflows when job B depends on the output of A.

**Comment by acecilia** [comment]
A bit more context about the setup. The carthage binaries are part of a bigger repository that is consuming such binaries. Everything works well because the versions used for the cache are fixed by the `cartfile.resolved`. But seems to be impossible to use `--no-skip-current` in such setup because the commit used as version by Rome changes every time, as the rest of the repository evolves and adds changes.

Let me know it above is clear :) 

A solution may be to move the current project out into their own repository with carthage support, so it can be consumed through the `cartfile`. Cant really think of an alternative way of assigning the version to the current modules 🤔

**Comment by tmspzz** [comment]
If you commit, the new hash will be used as version. 

Since in your case you can't write in the Cartfile.resolved the hash of the commit that will be (i.e. the one you're making) then you will always have a cache miss. 

You have to have another repository if you want to take advantage of the current map. I think it can even be nested in the current repository.
