### ISSUE TITLE
Rome crashes when downloading dependencies

### ISSUE THREAD

**Issue by mpdifran** [tmspzz/Rome#242]
## Bug Report 

Not sure what's causing this, but I'm getting an error when I run Rome.

**Steps which explain the enhancement or reproduce the bug**

1. Run this Rome command
```
swift_prefix=`xcrun swift --version | head -1 | sed 's/.*\((.*)\).*/\1/' | tr -d "()" | tr " " "-"`
rome download --platform iOS --cache-prefix $swift_prefix
```

Notes: 
- My Romefile is caching in a local directory as well as on s3.
- Rome was working fine earlier, and this error just started appearing sometime this week. We did not change the Romefile, update Rome, etc, which leads me to believe it's an issue with a particular archive.

**Current behavior**

I get the following output while downloading dependencies:

```
13:54:31 2021-01-21 - Found Kingfisher in local cache at: /Users/markdifranco/Library/Caches/Rome/swiftlang-1200.0.45-clang-1200.0.32.28/Kingfisher/iOS/Kingfisher.framework-5.15.8.zip
13:54:31 2021-01-21 - Starting to unzip Kingfisher.framework-5.15.8.zip
rome: Data.Binary.Get.runGet at position 1102: Did not find end of central directory signature
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.6.0:Data.Binary.Get
```

**Suggested behavior**

Rome does not error out.

**Rome version:** 

`0.23.3.64 - Romam uno die non fuisse conditam.`

**OS and version:** 

macOS version 11.1 (20C69)

**Comment by tmspzz** [comment]
The zip file is corrupted or needs to be replaced
