### ISSUE TITLE
Skip bcsymbolmaps and dsyms when uploading/downloading a framework

### ISSUE THREAD

**Issue by tmspzz** [tmspzz/Rome#248]
## Enhancement Suggestion

bcsymbolmaps and dsyms are already contained in the xcframework so they don't need to be uploaded or downloaded separately

**Current behavior**

    Rome attempts to upload/download bcsymbolmaps and dsyms when using --use-xcframeworks

**Suggested behavior**

    Rome **should not** attempt to upload/download bcsymbolmaps and dsyms when using --use-xcframeworks

**Why would the enhancement be useful to most users**

    Fewer errors on console

**Rome version:** 

    develop

**OS and version:** 

    independent of os and version

**Comment by tmspzz** [comment]
@mpdifran this one's on you to take care of please 👍

**Comment by mpdifran** [comment]
@tmspzz is there an ETA on when we'll see this in a release?

**Comment by tmspzz** [comment]
> @tmspzz is there an ETA on when we'll see this in a release?

Will make one today
