### ISSUE TITLE
Failed to install latest ROME in MAC

### ISSUE THREAD

**Issue by jageen-shukla** [tmspzz/Rome#253]
## Bug Report 

   Failed to install ROME using brew

**Steps which explain the enhancement or reproduce the bug**

1. Run command `brew install tmspzz/homebrew-tap/rome`

**Current behavior**

Giving error about outdated command line too version

```
==> Downloading https://github.com/blender/Rome/releases/download/v0.24.0.65/rome.zip
Already downloaded: /Users/jageen.shukla/Library/Caches/Homebrew/downloads/ec511669bed7143c37b9728e93a19e1a1745381f8c0c6db296e0acdc2ec54a93--rome.zip
==> Installing rome from tmspzz/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.
```

**Suggested behavior**
   It should run and install OR mention minimum env in read me file. 

**OS and version:** 
- OS : MacOS 12.1
- Xcode : 13.2.1

**Comment by tmspzz** [comment]
@jageen-shukla 

Your command line tools are out of date, as brew states.

> Installing rome from tmspzz/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force
